[Greeter]
clock-format=%a %b %-d  %H:%M
theme-name=Adwaita-dark
icon-theme-name=Adwaita
cursor-theme-name=Adwaita
enable-hidpi=true
draw-user-backgrounds=false
background=/usr/share/backgrounds/bing/BingWallpaper.jpg
