general.import = ["~/.config/alacritty/themes/vscode_dark+.toml"]

[window]
padding = { x = 10, y = 10 }

[font]
normal.family = "BlexMono Nerd Font"
bold.family = "BlexMono Nerd Font"
italic.family = "BlexMono Nerd Font"
bold_italic.family = "BlexMono Nerd Font"
size = 11.0
